GET http://localhost:3000/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.dXNlcjE.NS8JkbCfkcmgF1l2dIlF4aw8Qga0K3KS0-pt9ElPd0c

###

POST http://localhost:3000/task
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.dXNlcjE.NS8JkbCfkcmgF1l2dIlF4aw8Qga0K3KS0-pt9ElPd0c

{
    "id":"0000",
    "name":"00000",
    "start":"20/06/2022",
    "end":"21/06/2022", 
    "content":"Lekcje z jasiem",
    "tags":"628bf4921d0282adb72a875b",
    "employee":"628bf4921d0282adb72a875b"
}